# Generated by Django 5.2.4 on 2025-10-02 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=255)),
                ('short_desc', models.TextField(default='')),
                ('long_desc', models.TextField(default='')),
                ('long_desc_generating', models.BooleanField(default=False)),
                ('source', models.TextField(default='')),
                ('in_storyboard', models.BooleanField(default=False)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('has_order', models.BooleanField(default=False)),
                ('order_num', models.IntegerField(default=0)),
                ('last_saved', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JupyterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cell_type', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('metadata', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=list)),
                ('execution_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_headers', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'jupyter_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NarrativeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField(default='')),
                ('order', models.JSONField(default=list)),
                ('theme', models.TextField(default='')),
                ('categories', models.JSONField(default=list)),
                ('sequence_justification', models.TextField(default='')),
            ],
            options={
                'db_table': 'narrative_cache',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.JSONField(default=dict)),
                ('request_headers', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_actions',
                'managed': True,
            },
        ),
    ]
