# Generated by Django 5.2.4 on 2025-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='in_storyboard',
            field=models.BooleanField(default=True),
        ),
    ]
