# Generated by Django 5.2.4 on 2025-11-17 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagedata_in_storyboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraction',
            name='element',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraction',
            name='state_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('click', 'Click'), ('hover', 'Hover'), ('drag', 'Drag'), ('drop', 'Drop')], default='click', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Group', max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('cards', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_data',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='imagedata',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api.groupdata'),
        ),
        migrations.CreateModel(
            name='MousePositionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mouse_pos_batch', models.JSONField(default=list)),
                ('request_headers', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='storystudio_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mouse_position_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScrollLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scroll_batch', models.JSONField(default=list)),
                ('request_headers', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='scroll_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scroll_logs',
                'managed': True,
            },
        ),
    ]
