# Generated by Django 6.0.2 on 2026-02-20 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagedata_index_useraction_element_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdata',
            name='cards',
        ),
        migrations.AddField(
            model_name='groupdata',
            name='scaffold_group_number',
            field=models.IntegerField(blank=True, help_text='Group number within scaffold (1=causes, 2=effects, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='scaffold_group_number',
            field=models.IntegerField(blank=True, help_text='Group number within scaffold (1=causes, 2=effects, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='narrativecache',
            name='story_structure_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ScaffoldData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='No Scaffold', max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('valid_group_numbers', models.JSONField(default=list, help_text='List of valid group numbers for this scaffold (1=causes, 2=effects, etc.)')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='scaffold_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scaffold_data',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='groupdata',
            name='scaffold_id',
            field=models.ForeignKey(blank=True, db_column='scaffold_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.scaffolddata'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='scaffold_id',
            field=models.ForeignKey(blank=True, db_column='scaffold_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='api.scaffolddata'),
        ),
    ]
