# Generated by Django 5.2.4 on 2026-04-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_groupdata_cards_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=64)),
                ('task_id', models.CharField(max_length=255)),
                ('current_stage', models.IntegerField(default=0)),
                ('total_stages', models.IntegerField(default=1)),
                ('stage_name', models.CharField(default='', max_length=255)),
                ('substage', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_progress',
                'managed': True,
                'indexes': [models.Index(fields=['task_id'], name='task_progre_task_id_22502d_idx'), models.Index(fields=['user', 'task_type'], name='task_progre_user_id_bc7c0b_idx')],
            },
        ),
    ]
