# Generated by Django 5.2.4 on 2026-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotate_with_ai', models.BooleanField(default=True)),
                ('select_with_ai', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'feature_flags',
                'managed': True,
            },
        ),
    ]
