# Generated by Django 5.2.13 on 2026-05-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_study_studyreferralcode'),
        ('users', '0002_user_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.ForeignKey(blank=True, db_column='study_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='api.study'),
        ),
    ]
